name: CI
on:
  workflow_dispatch:
#env:
#  BUCKET_NAME : "<example-bucket-name>"
#  AWS_REGION : "<example-aws-region>"

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

#      - name: configure aws credentials
#        uses: aws-actions/configure-aws-credentials@v2
#        with:
#          role-to-assume: arn:aws:iam::1234567890:role/example-role
#          role-session-name: samplerolesession
#          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Lint Python code
        run: |
          python -m black .
          git diff --exit-code

      - name: Unit Tests
        run: echo "Unit Tests Placeholder"

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMG_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}

      - name: Metadata debug
        run: |
          echo "Tags: ${{ steps.metadata.outputs.tags }}"
          echo "Labels: ${{ steps.metadata.outputs.labels }}"

#      - name: Build and push Docker image
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          push: ${{ github.event.base_ref =='refs/heads/main' && github.ref_type == 'tag'}}
#          tags: ${{ steps.metadata.outputs.tags }}
#          labels: ${{ steps.metadata.outputs.labels }}
